{% set name = "wagtail-dynamic-dropdown" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-dynamic-dropdown-{{ version }}.tar.gz
  sha256: 3d18e405afeefacc9b9b908ad72919c8482a8973ebc6c8243bcdb786888d4c0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - wagtail_dynamic_dropdown
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LilJack118/wagtail-dynamic-dropdown
  summary: A Django application which allow to use dynamically defined choices that will be updated every time the user opens edit/create page. Moreover, the choices are not migrated to the database.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
